[metadata]
name = mujpy
version = attr: mujpy._version.__version__
description = muSR data analysis classes with jupyterlab ipywidgets GUI
author = Roberto De Renzi
author_email = roberto.derenzi@unipr.it
url= https://github.com/RDeRenzi/mujpy'
keywords = muSR data analysis
long_description = file: README.md
long_description_content_type = text/markdown
license = GPLv3
classifiers = 
  Intended Audience :: Science/Research
  License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)
  Programming Language :: Python
  Programming Language :: Python :: 3
  Programming Language :: Python :: 3.10
  Programming Language :: Python :: 3.11
  Programming Language :: Python :: 3.12
  Programming Language :: Python :: 3.13
  Programming Language :: Python :: 3.14
  Programming Language :: Python :: 3 :: Only
  Framework :: Jupyter
  Operating System :: OS Independent
  Topic :: Scientific/Engineering :: Physics

[options]
python_requires = >=3.7
requires = [
		'setuptools',
		'numpy',
		'nexusformat',
		'uproot',
		'musr2py',
		'scipy',
		'sympy',
		'iminuit',
		'jupyterlab',
		'ipympl',
		'ipywidgets',
		'fonttools'
		]
zip_safe = False

